# Generated by Django 5.1.7 on 2025-03-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(null=True, upload_to='music/images/'),
        ),
    ]
